spring.application.name=gestionProductos

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/db_gestionProductosHabanaCrem
spring.datasource.username=postgres
spring.datasource.password=nieves@

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false
